# Generated by Django 4.2.4 on 2023-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SAC', '0002_atendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='ativo_atend',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='atualizado_em_atend',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
